### ISSUE TITLE
ローカルでのPHPプログラムの変更がサーバー側に反映されるのに時間がかかる

### ISSUE THREAD

**Issue by Neleid** [thingsym/vaw#1]
ローカルのPHPプログラムを変更しても、サーバー側に反映されるのにおおむね30〜40秒程度の遅延が発生します。
httpd.confのEnableSendfileはoffとなっています。（もともとそうなっていますが）
vccwの時はそのようなことがなかったのですが、何か心当たりあるでしょうか？ 

環境は、以下になります。
osx el capitan
virtualbox 5.0.16
vagrant 1.8.1
vaw 最新版(masterをダウンロード)

追記：
なお、ローカルのファイルと仮想OS上のファイルの同期そのものは即時反映されます。
なので、動作としてはちょうどキャッシュされたPHPファイルが実行されているイメージです。

**Comment by Neleid** [comment]
OPCacheのせいでした。
自己解決しました。

**Comment by thingsym** [comment]
ご報告ありがとうございます。
開発しやすいように見直しをしてみたいと思います。
よろしくお願いいたします。

**Comment by thingsym** [comment]
How to disable OPcache.

In the case of php 5.6.12, Apache, CentOS 6

1. open php.ini
 `sudo vi /home/vagrant/.phpenv/versions/5.6.12/etc/php.ini`

2. edit php.ini

 change from `opcache.enable=1` to `opcache.enable=0`

3. server restart

 `sudo service httpd restart`

**Comment by Neleid** [comment]
OPcacheの無効化方法ありがとうございます。
上記の方法でもできますが、これだとPHPのバージョンごとに設定しないといけないので、私の場合は/var/www/html直下の.htaccessに以下の行を追加しました。

php_flag opcache.enable Off

WordPressのプラグイン開発ではwp-content/plugins以下のみOPcacheを無効化できればいいのですが、そこに.htaccessを置いても無効化できませんでした。
多分私の勉強不足だとは思います。
